name: lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint black isort mypy

      - name: Analysing the code with pylint
        run: |
          pylint --rcfile .pylintrc $(git ls-files */src/*.py */tests/*.py)

      - name: check format with black
        run: |
          black --check $(git ls-files */src/*.py */tests/*.py)
