name: Pylint

on: [push]
jobs:
  build:
    runs-on: python:3.10.6-bullseye
    steps:
    - name: Install dependencies
      run:
        python -m pip install --upgrade pip
        pip install pylint
    - name: lint
      run: pylint $(git ls-files '*.py')
